# Dataset configuration
data:
  name: "wine_quality"  # Using Wine Quality dataset
  train_size: 0.8
  batch_size: 64
  random_state: 42

# Training configuration
training:
  device: "cuda"  # Options: "cuda", "cpu"
  epochs: 2000
  learning_rate: 0.001
  weight_decay: 0.0001
  patience: 50

# Model configuration
model:
  hidden_dim: 128
  prior_std: 1.0
  dropout_rate: 0.2

# SGLD configuration
sgld:
  learning_rate: 0.0005
  temperature: 0.5
  epochs: 1000
  prior_std: 0.5
  sampling_percentage: 0.5
  num_ensemble_models: 10

# Paths configuration
paths:
  logs: "BasicTraining/logs"
  plots: "BasicTraining/plots"
  models: "BasicTraining/models"

# Random Seed
random_seed: 42 